---
- name: Update brew
  community.general.homebrew:
    update_homebrew: true
- name: Install brew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
- name: Install brew casks
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
